trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'DevOpsWebinar.csproj'
      arguments: '--configuration Release'
      zipAfterPublish: false
      modifyOutputPath: false
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure DevOps Webinar'
      appType: 'webApp'
      WebAppName: 'devops-webinar'
      packageForLinux: 'bin\Release\netcoreapp3.1\publish\'